In [1]:
import pandas as pd
import matplotlib
%matplotlib inline

In [2]:
# - Szenario1: "an einem wochentag in 13-15 uhr erwarte ich soviele menschen in der gegend"

In [3]:
!pwd #mit ausrufezeichen ist ein shell befehl, wo ich mein Pfad check

/Users/maryammirza/PycharmProjects/pedestrian_forecast_datascience/src

In [4]:
df3310 = pd.read_csv('../data/bzm_telraam_9000003310.csv.gz.csv')
df4118 = pd.read_csv('../data/bzm_telraam_9000004118.csv.gz.csv')
df4602 = pd.read_csv('../data/bzm_telraam_9000004602.csv.gz.csv')
df4685 = pd.read_csv('../data/bzm_telraam_9000004685.csv.gz.csv')
df5444 = pd.read_csv('../data/bzm_telraam_9000005444.csv.gz.csv')
df5832 = pd.read_csv('../data/bzm_telraam_9000005832.csv.gz.csv')

dftotal= pd.concat([df3310, df4118, df4602, df4685, df5444, df5832], ignore_index=True)

In [5]:
#die ersten 5 zeilen anschauen
dftotal.head()

,segment_id,date_local,uptime,ped_lft,ped_rgt,ped_total,bike_lft,bike_rgt,bike_total,car_lft,...,heavy_total,v85,car_speed0,car_speed10,car_speed20,car_speed30,car_speed40,car_speed50,car_speed60,car_speed70
0,9000003310,2022-03-18 07:00,0.752500,3,1,4,19,15,33,73,...,0,24.5,8.77,47.37,36.84,6.14,0.88,0.0,0.00,0.00
1,9000003310,2022-03-18 08:00,0.797222,6,3,9,25,18,43,99,...,0,20.0,12.90,65.16,18.71,2.58,0.00,0.0,0.00,0.65
2,9000003310,2022-03-18 09:00,0.795833,0,1,1,23,13,35,83,...,0,21.0,16.18,54.41,26.47,1.47,0.74,0.0,0.74,0.00
3,9000003310,2022-03-18 10:00,0.805556,1,4,5,15,14,29,81,...,0,21.0,11.29,59.68,25.81,3.23,0.00,0.0,0.00,0.00
4,9000003310,2022-03-18 11:00,0.596667,3,0,3,30,18,49,77,...,0,22.5,18.18,45.45,32.47,1.30,1.30,1.3,0.00,0.00

In [6]:
#Wie viele zeilen und spalten hat der Datensatz?
dftotal.shape

(85782, 24)

In [7]:
dftotal.dtypes

segment_id       int64
date_local      object
uptime         float64
ped_lft          int64
ped_rgt          int64
ped_total        int64
bike_lft         int64
bike_rgt         int64
bike_total       int64
car_lft          int64
car_rgt          int64
car_total        int64
heavy_lft        int64
heavy_rgt        int64
heavy_total      int64
v85            float64
car_speed0     float64
car_speed10    float64
car_speed20    float64
car_speed30    float64
car_speed40    float64
car_speed50    float64
car_speed60    float64
car_speed70    float64
dtype: object

In [8]:
#Datum umwandeln
dftotal["date_local"] = pd.to_datetime(dftotal["date_local"])

In [9]:
dftotal.dtypes

segment_id              int64
date_local     datetime64[ns]
uptime                float64
ped_lft                 int64
ped_rgt                 int64
ped_total               int64
bike_lft                int64
bike_rgt                int64
bike_total              int64
car_lft                 int64
car_rgt                 int64
car_total               int64
heavy_lft               int64
heavy_rgt               int64
heavy_total             int64
v85                   float64
car_speed0            float64
car_speed10           float64
car_speed20           float64
car_speed30           float64
car_speed40           float64
car_speed50           float64
car_speed60           float64
car_speed70           float64
dtype: object

In [10]:
#describe gibt mir statistische übersicht über numerische spalten (geht nicht für strings, nan)
dftotal.describe()

,segment_id,date_local,uptime,ped_lft,ped_rgt,ped_total,bike_lft,bike_rgt,bike_total,car_lft,...,heavy_total,v85,car_speed0,car_speed10,car_speed20,car_speed30,car_speed40,car_speed50,car_speed60,car_speed70
count,8.578200e+04,85782,85782.000000,85782.000000,85782.000000,85782.000000,85782.000000,85782.000000,85782.000000,85782.000000,...,85782.000000,78727.000000,85782.000000,85782.000000,85782.000000,85782.000000,85782.00000,85782.000000,85782.000000,85782.000000
mean,9.000005e+09,2024-07-25 22:54:55.656431360,0.734979,7.739374,11.107120,18.850108,26.146872,25.146931,51.290119,91.938204,...,32.457672,33.347632,11.019576,25.952541,32.648394,13.126994,4.53855,1.806582,0.922829,1.971187
min,9.000003e+09,2022-03-18 07:00:00,0.000278,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,2.500000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
25%,9.000004e+09,2023-11-14 10:15:00,0.670000,0.000000,0.000000,1.000000,8.000000,5.000000,15.000000,18.000000,...,5.000000,25.500000,2.130000,12.500000,23.080000,4.000000,0.00000,0.000000,0.000000,0.000000
50%,9.000005e+09,2024-08-14 16:00:00,0.768333,3.000000,3.000000,6.000000,20.000000,17.000000,39.000000,46.000000,...,17.000000,29.000000,7.210000,26.670000,34.290000,9.460000,1.70000,0.000000,0.000000,0.000000
75%,9.000005e+09,2025-05-21 23:45:00,0.795833,9.000000,10.000000,18.000000,38.000000,38.000000,75.000000,97.000000,...,45.000000,37.000000,14.917500,38.360000,43.940000,20.000000,6.25000,1.820000,0.560000,1.230000
max,9.000006e+09,2026-02-04 16:00:00,1.068890,1800.000000,488.000000,1800.000000,423.000000,720.000000,720.000000,1200.000000,...,1804.000000,124.000000,100.000000,100.000000,133.330000,100.000000,100.00000,100.000000,100.000000,100.000000
std,8.235215e+02,NaN,0.210115,14.917615,25.193362,37.663975,24.608280,26.122534,47.221426,124.245948,...,39.980207,13.665198,13.048895,16.973693,17.222695,12.465653,7.21919,4.362390,3.129499,5.795191

In [11]:
#Anzahl der fehlenden Werte in jeder Spalte:
dftotal.isna().sum() # isna steht für missing values

segment_id        0
date_local        0
uptime            0
ped_lft           0
ped_rgt           0
ped_total         0
bike_lft          0
bike_rgt          0
bike_total        0
car_lft           0
car_rgt           0
car_total         0
heavy_lft         0
heavy_rgt         0
heavy_total       0
v85            7055
car_speed0        0
car_speed10       0
car_speed20       0
car_speed30       0
car_speed40       0
car_speed50       0
car_speed60       0
car_speed70       0
dtype: int64

In [12]:
#Prozent der fehlenden Werte in jeder Spalte:
dftotal.isna().mean()
#1 steht für 100 Prozent, da wo 1.0 steht = fehlen alle Werte
# und wo 0.0 steht = keine Werte fehlen.

segment_id     0.000000
date_local     0.000000
uptime         0.000000
ped_lft        0.000000
ped_rgt        0.000000
ped_total      0.000000
bike_lft       0.000000
bike_rgt       0.000000
bike_total     0.000000
car_lft        0.000000
car_rgt        0.000000
car_total      0.000000
heavy_lft      0.000000
heavy_rgt      0.000000
heavy_total    0.000000
v85            0.082243
car_speed0     0.000000
car_speed10    0.000000
car_speed20    0.000000
car_speed30    0.000000
car_speed40    0.000000
car_speed50    0.000000
car_speed60    0.000000
car_speed70    0.000000
dtype: float64

In [13]:
#Mittelwerte Baseline Modell:
#mit groupby wird nach Stunden gruppiert und die Stunde raus extrahiert
stuendlichemittelwerte= dftotal.groupby(dftotal["date_local"].dt.hour).mean() #hiermit gruppiere ich nach stunden und berechne den mittelwert

In [14]:
stuendlichemittelwerte #alle mittelwerte

,segment_id,date_local,uptime,ped_lft,ped_rgt,ped_total,bike_lft,bike_rgt,bike_total,car_lft,...,heavy_total,v85,car_speed0,car_speed10,car_speed20,car_speed30,car_speed40,car_speed50,car_speed60,car_speed70
date_local,,,,,,,,,,,,,,,,,,,,,
0,9.000005e+09,2025-04-12 15:45:18.367346944,0.998628,0.000000,0.000000,0.000000,0.003401,0.003401,0.006803,0.015306,...,0.000000,49.250000,0.190782,0.055595,0.000000,0.027245,0.013078,0.000000,0.026156,0.027245
1,9.000005e+09,2025-04-12 09:39:23.076922880,0.991073,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,9.000005e+09,2025-04-14 05:08:27.382550528,0.992937,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,9.000005e+09,2025-04-13 17:12:47.512690432,0.993504,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,9.000005e+09,2024-11-25 09:23:57.674919168,0.672933,0.201292,0.106566,0.307858,0.683531,0.584499,1.270183,8.142088,...,2.440258,35.360841,2.687675,5.442131,11.729882,8.441819,3.316114,0.965005,0.224844,0.690861
5,9.000005e+09,2024-08-13 10:29:33.321708800,0.570603,2.059721,1.762424,3.827376,3.680035,2.670009,6.348300,21.485179,...,8.262860,36.529977,4.033609,15.149861,32.271966,16.104547,5.929887,1.755519,0.770466,2.158862
6,9.000005e+09,2024-07-10 15:50:20.873921280,0.648815,3.261898,4.341497,7.612302,8.113832,6.564987,14.676037,43.290287,...,22.135263,35.673444,5.304008,20.153858,36.494534,18.200584,6.112360,2.205043,0.957531,1.833148
7,9.000005e+09,2024-07-03 20:52:54.293059072,0.660313,7.684398,9.117461,16.805616,18.733043,19.775756,38.499110,74.668183,...,30.487245,33.882741,9.201946,26.096939,36.354254,16.018632,5.461722,1.828752,0.795592,2.155068
8,9.000005e+09,2024-07-09 06:31:45.331599360,0.720016,10.602243,11.638004,22.244148,26.338914,28.805592,55.144993,90.354519,...,35.382640,33.439542,10.859361,29.261874,34.875140,14.408379,5.309210,1.922123,0.991403,2.171091
9,9.000005e+09,2024-07-09 02:20:19.477357568,0.774022,10.478818,12.354813,22.840773,24.174809,25.954715,50.107937,91.041227,...,36.897744,32.907257,12.595004,29.332777,34.556598,13.679726,4.760568,1.872526,0.954921,2.031727
10,9.000005e+09,2024-07-09 14:13:11.824817408,0.768180,8.147770,10.126034,18.274290,22.955718,21.796918,44.754096,93.117113,...,39.174047,32.453710,14.613817,28.443072,34.190232,13.410018,4.460075,1.750972,0.853719,1.992947
11,9.000005e+09,2024-07-10 07:06:22.755267584,0.754565,7.028039,9.490762,16.525608,24.017990,23.128039,47.145219,98.617990,...,43.810697,30.873821,18.280217,28.671791,32.546598,12.270611,4.028660,1.588972,0.800160,1.539919
12,9.000005e+09,2024-07-10 14:32:04.983777024,0.752461,7.529040,10.951817,18.487184,27.998378,25.916775,53.913530,103.611616,...,43.648280,31.080508,16.875102,28.934625,33.297594,12.515610,3.979740,1.616553,0.835756,1.540808
13,9.000005e+09,2024-07-11 01:50:49.740932608,0.758055,8.139734,11.985427,20.134553,30.289670,30.607351,60.885525,108.351684,...,40.101360,32.363096,13.582382,28.223506,35.476362,13.582324,4.273663,1.758261,0.847158,1.743093
14,9.000005e+09,2024-07-10 17:21:36.560675072,0.768841,9.823329,14.786016,24.612427,32.318138,31.158825,63.469825,122.410286,...,40.070896,33.590479,12.671527,27.576051,35.705107,14.005532,4.567391,1.883405,1.019507,2.123434
15,9.000005e+09,2024-07-10 15:34:22.822803456,0.746279,11.063667,17.439825,28.500731,36.696118,34.605002,71.303882,131.082345,...,40.847328,34.293441,10.960866,27.485672,36.207952,14.193299,5.088342,2.194869,1.170352,2.339310
16,9.000005e+09,2024-07-08 03:54:58.346196224,0.691742,9.679713,16.838479,26.519294,37.821022,33.834068,71.648107,120.174017,...,36.482911,34.498793,10.222900,27.955917,35.963528,13.899162,5.053497,2.210581,1.279576,2.525522
17,9.000005e+09,2024-06-29 00:00:51.520572416,0.737056,9.536896,17.946556,27.498211,39.106664,35.786673,74.904741,115.385063,...,31.598390,34.505502,9.079177,28.344682,33.878652,13.206939,4.962909,2.265725,1.263907,2.587381
18,9.000005e+09,2024-07-13 19:44:56.535796736,0.707787,7.941750,14.699769,22.645368,39.721324,36.830126,76.553759,110.291506,...,27.816269,34.426543,9.382692,28.615676,32.759995,12.796554,4.668412,2.083788,1.164036,2.675920
19,9.000005e+09,2024-07-21 23:24:05.353159936,0.731493,6.090458,9.794919,15.886927,33.068773,30.201983,63.268897,90.632280,...,20.814126,34.358860,8.866518,27.750412,32.012875,12.128135,4.449901,1.866599,0.977069,2.397200
20,9.000005e+09,2024-08-16 03:52:48.624359424,0.664168,4.151360,5.626724,9.768230,23.886874,22.035081,45.904218,69.205361,...,12.547891,33.805037,6.891013,26.336039,31.086831,11.930343,4.224907,1.787201,0.859503,1.926121
21,9.000005e+09,2024-09-23 11:10:36.008091648,0.546610,2.165206,2.107889,4.251517,14.584626,11.935266,26.525287,40.428186,...,6.781524,33.441147,5.354403,20.477249,25.066649,9.969703,3.593338,1.435401,0.784862,1.492454
22,9.000005e+09,2025-04-12 07:32:35.329949184,0.997240,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,18.500000,0.169205,0.000000,0.112809,0.056396,0.000000,0.000000,0.000000,0.000000
23,9.000005e+09,2025-04-12 22:57:33.559322112,0.997994,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,6.500000,0.169492,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [15]:
#Wie viel Leute zwischen 13 und 14 uhr erwarte ich im gesamten Umkreis im Durchschnitt aller Station?
#von 13-14 Uhr ist der Durschnitt für pedtotal= 20.134553.

#Wie viel Leute zwischen 13 und 15 uhr erwarte ich im gesamten Umkreis im Durchschnitt aller Station?
#von 13-14 Uhr ist der Durchnitt für pedtotal= 20.134553 + 24.612427 = 44.74698.
#Das Modell berücksichtigt keine Unterschiede zwischen den Tagen, also dass z.b. am Mo unterschiedlich viele Leute unterwegs sind als am So.

In [16]:
#Zweites Baseline Modell: Mittelwert pro Stunde und pro Station
station_stuendlichemittelwerte = dftotal.groupby([dftotal["date_local"].dt.hour, "segment_id"]).mean() #hiermit gruppiere ich nach stunden und station und berechne den mittelwert

In [17]:
dftotal.segment_id.value_counts()

segment_id
9000005444    18349
9000003310    15800
9000004118    13980
9000004602    13841
9000004685    13587
9000005832    10225
Name: count, dtype: int64

In [18]:
station_stuendlichemittelwerte

                                         date_local    uptime   ped_lft  \
date_local segment_id
0          9000005444 2025-04-12 15:45:18.367346944  0.998628  0.000000
1          9000005444 2025-04-12 09:39:23.076922880  0.991073  0.000000
2          9000005444 2025-04-14 05:08:27.382550528  0.992937  0.000000
3          9000005444 2025-04-13 17:12:47.512690432  0.993504  0.000000
4          9000003310 2023-09-14 08:58:22.702702592  0.101019  0.198198
...                                             ...       ...       ...
21         9000005832 2024-12-04 08:04:36.923076864  0.099863  8.569231
22         9000004118 2025-09-29 22:00:00.000000000  0.338056  0.000000
           9000005444 2025-04-12 00:36:12.203389696  0.998357  0.000000
23         9000004118 2025-09-29 23:00:00.000000000  0.129167  0.000000
           9000005444 2025-04-12 16:01:56.129032192  0.999469  0.000000

                        ped_rgt  ped_total   bike_lft   bike_rgt  bike_total  \
date_local segment_id
0          9000005444  0.000000   0.000000   0.003401   0.003401    0.006803
1          9000005444  0.000000   0.000000   0.000000   0.000000    0.000000
2          9000005444  0.000000   0.000000   0.000000   0.000000    0.000000
3          9000005444  0.000000   0.000000   0.000000   0.000000    0.000000
4          9000003310  0.000000   0.198198   0.288288   0.315315    0.603604
...                         ...        ...        ...        ...         ...
21         9000005832  6.153846  14.692308  75.753846  50.200000  126.107692
22         9000004118  0.000000   0.000000   0.000000   0.000000    0.000000
           9000005444  0.000000   0.000000   0.000000   0.000000    0.000000
23         9000004118  0.000000   0.000000   0.000000   0.000000    0.000000
           9000005444  0.000000   0.000000   0.000000   0.000000    0.000000

                         car_lft    car_rgt  ...  heavy_total        v85  \
date_local segment_id                        ...
0          9000005444   0.015306   0.027211  ...     0.000000  49.250000
1          9000005444   0.000000   0.000000  ...     0.000000        NaN
2          9000005444   0.000000   0.000000  ...     0.000000        NaN
3          9000005444   0.000000   0.000000  ...     0.000000        NaN
4          9000003310   4.450450   7.783784  ...     1.153153  31.793333
...                          ...        ...  ...          ...        ...
21         9000005832  31.430769  46.369231  ...     3.846154  28.217742
22         9000004118   0.000000   5.000000  ...     0.000000   4.000000
           9000005444   0.000000   0.011864  ...     0.000000  33.000000
23         9000004118   0.000000   0.000000  ...     0.000000        NaN
           9000005444   0.000000   0.001698  ...     0.000000   6.500000

                       car_speed0  car_speed10  car_speed20  car_speed30  \
date_local segment_id
0          9000005444    0.190782     0.055595     0.000000     0.027245
1          9000005444    0.000000     0.000000     0.000000     0.000000
2          9000005444    0.000000     0.000000     0.000000     0.000000
3          9000005444    0.000000     0.000000     0.000000     0.000000
4          9000003310    4.684595     5.885766    30.210270    21.681441
...                           ...          ...          ...          ...
21         9000005832   11.910154    29.616462    37.948923    13.506462
22         9000004118  100.000000     0.000000     0.000000     0.000000
           9000005444    0.000000     0.000000     0.113000     0.056492
23         9000004118    0.000000     0.000000     0.000000     0.000000
           9000005444    0.169779     0.000000     0.000000     0.000000

                       car_speed40  car_speed50  car_speed60  car_speed70
date_local segment_id
0          9000005444     0.013078     0.000000     0.026156     0.027245
1          9000005444     0.000000     0.000000     0.000000     0.000000
2          9000005444     0.000000     0.000000     0.000000     0.000000
3          9000005444     0.000000     0.000000     0.000000     0.000000
4          9000003310     4.534414     1.801802     0.000000     0.300270
...                            ...          ...          ...          ...
21         9000005832     2.952615     0.137385     0.879077     0.305385
22         9000004118     0.000000     0.000000     0.000000     0.000000
           9000005444     0.000000     0.000000     0.000000     0.000000
23         9000004118     0.000000     0.000000     0.000000     0.000000
           9000005444     0.000000     0.000000     0.000000     0.000000

[116 rows x 23 columns]

In [19]:
#Zwischen 13 und 15 Uhr bei Station 9000003310 erwarte ich im Durchschnitt 3.712712 + 5.121289 = 8.834001 Fußgänger.

In [20]:
#Evaluation des station_stuendlichemittelwerte BaselineModells:
#TODO: Vorher hätte Train Test Split gemacht werden müssen
# TODO: Modell auf den Trainingsdaten ausrechnen
# TODO: Vorhersage für eine Station und einen Zeitraum

In [21]:
# Erstes einfaches Modell: Lineare Regression
df_wetter = pd.read_csv('../data/produkt_klima_tag_19480101_20241231_00433.txt',sep=';')

In [22]:
df_wetter.head()

,STATIONS_ID,MESS_DATUM,QN_3,FX,FM,QN_4,RSK,RSKF,SDK,SHK_TAG,NM,VPM,PM,TMK,UPM,TXK,TNK,TGK,eor
0,433,19480101,-999,-999.0,-999.0,5,5.7,8,-999.0,4,5.0,4.9,1010.7,-1.8,89.0,0.8,-5.0,-4.7,eor
1,433,19480102,-999,-999.0,-999.0,5,3.3,1,-999.0,8,8.0,7.9,999.7,4.4,95.0,6.8,-2.7,-2.5,eor
2,433,19480103,-999,-999.0,-999.0,5,4.0,1,-999.0,0,5.3,9.8,1001.7,8.5,86.0,10.6,5.2,4.6,eor
3,433,19480104,-999,-999.0,-999.0,5,0.2,1,-999.0,0,8.0,10.2,999.8,10.2,83.0,11.5,6.6,4.7,eor
4,433,19480105,-999,-999.0,-999.0,5,2.0,1,-999.0,0,7.7,9.8,987.8,10.5,78.0,12.0,8.0,5.9,eor

In [23]:
#Mess_datum in ein Datum umwandeln
df_wetter["MESS_DATUM"] = pd.to_datetime(df_wetter["MESS_DATUM"], format="%Y%m%d") #hiermit wird das Datum umgewandelt, damit es in Zukunft einfacher zu handhaben ist. Das Format ist JahrMonatTag, deswegen %Y%md%Y%m%d

In [24]:
df_wetter.head()

,STATIONS_ID,MESS_DATUM,QN_3,FX,FM,QN_4,RSK,RSKF,SDK,SHK_TAG,NM,VPM,PM,TMK,UPM,TXK,TNK,TGK,eor
0,433,1948-01-01,-999,-999.0,-999.0,5,5.7,8,-999.0,4,5.0,4.9,1010.7,-1.8,89.0,0.8,-5.0,-4.7,eor
1,433,1948-01-02,-999,-999.0,-999.0,5,3.3,1,-999.0,8,8.0,7.9,999.7,4.4,95.0,6.8,-2.7,-2.5,eor
2,433,1948-01-03,-999,-999.0,-999.0,5,4.0,1,-999.0,0,5.3,9.8,1001.7,8.5,86.0,10.6,5.2,4.6,eor
3,433,1948-01-04,-999,-999.0,-999.0,5,0.2,1,-999.0,0,8.0,10.2,999.8,10.2,83.0,11.5,6.6,4.7,eor
4,433,1948-01-05,-999,-999.0,-999.0,5,2.0,1,-999.0,0,7.7,9.8,987.8,10.5,78.0,12.0,8.0,5.9,eor

In [25]:
#Zusätzliche Spalten für Tag, Monat, Jahr
df_wetter["day"] = df_wetter["MESS_DATUM"].dt.day
df_wetter["month"] = df_wetter["MESS_DATUM"].dt.month
df_wetter["year"] = df_wetter["MESS_DATUM"].dt.year

In [45]:
df_wetter.isna().sum()

STATIONS_ID    0
MESS_DATUM     0
QN_3           0
FX             0
FM             0
QN_4           0
RSK            0
RSKF           0
SDK            0
SHK_TAG        0
NM             0
VPM            0
PM             0
TMK            0
UPM            0
TXK            0
TNK            0
TGK            0
eor            0
day            0
month          0
year           0
dtype: int64

In [26]:
df_wetter.head()

,STATIONS_ID,MESS_DATUM,QN_3,FX,FM,QN_4,RSK,RSKF,SDK,SHK_TAG,...,PM,TMK,UPM,TXK,TNK,TGK,eor,day,month,year
0,433,1948-01-01,-999,-999.0,-999.0,5,5.7,8,-999.0,4,...,1010.7,-1.8,89.0,0.8,-5.0,-4.7,eor,1,1,1948
1,433,1948-01-02,-999,-999.0,-999.0,5,3.3,1,-999.0,8,...,999.7,4.4,95.0,6.8,-2.7,-2.5,eor,2,1,1948
2,433,1948-01-03,-999,-999.0,-999.0,5,4.0,1,-999.0,0,...,1001.7,8.5,86.0,10.6,5.2,4.6,eor,3,1,1948
3,433,1948-01-04,-999,-999.0,-999.0,5,0.2,1,-999.0,0,...,999.8,10.2,83.0,11.5,6.6,4.7,eor,4,1,1948
4,433,1948-01-05,-999,-999.0,-999.0,5,2.0,1,-999.0,0,...,987.8,10.5,78.0,12.0,8.0,5.9,eor,5,1,1948

In [27]:
dftotal["day"] = dftotal["date_local"].dt.day
dftotal["month"] = dftotal["date_local"].dt.month
dftotal["year"] = dftotal["date_local"].dt.year

In [28]:
dftotal.head()

,segment_id,date_local,uptime,ped_lft,ped_rgt,ped_total,bike_lft,bike_rgt,bike_total,car_lft,...,car_speed10,car_speed20,car_speed30,car_speed40,car_speed50,car_speed60,car_speed70,day,month,year
0,9000003310,2022-03-18 07:00:00,0.752500,3,1,4,19,15,33,73,...,47.37,36.84,6.14,0.88,0.0,0.00,0.00,18,3,2022
1,9000003310,2022-03-18 08:00:00,0.797222,6,3,9,25,18,43,99,...,65.16,18.71,2.58,0.00,0.0,0.00,0.65,18,3,2022
2,9000003310,2022-03-18 09:00:00,0.795833,0,1,1,23,13,35,83,...,54.41,26.47,1.47,0.74,0.0,0.74,0.00,18,3,2022
3,9000003310,2022-03-18 10:00:00,0.805556,1,4,5,15,14,29,81,...,59.68,25.81,3.23,0.00,0.0,0.00,0.00,18,3,2022
4,9000003310,2022-03-18 11:00:00,0.596667,3,0,3,30,18,49,77,...,45.45,32.47,1.30,1.30,1.3,0.00,0.00,18,3,2022

In [29]:
# Spaltennamen fixen- Leerzeichen entfernen
df_wetter.columns = df_wetter.columns.str.strip()  # Entfernt Leerzeichen am Anfang und Ende

In [47]:
# Beide DataFrames mergen (zusammenführen)
df_alles = pd.merge(
    dftotal,
    df_wetter[["RSK", "SHK_TAG", "TMK", "STATIONS_ID", "MESS_DATUM", "year", "month", "day"]],
    left_on=["year", "month", "day"],
    right_on=["year", "month", "day"],
    how="inner" #inner schmeißt alles raus was nicht in beiden DataFrames steht
)

In [50]:
df_alles.shape

(53744, 32)

In [51]:
#Beide Dataphrames zusammen mergen
#Variablen die wir nutzen wollen:
# STATIONS_ID(Station ID), Typ: VARCHAR2
#MESS_DATUM(Referenzdatum), Typ: NUMBER YYYYMMDD
#RSK (tägliche Niederschlagshöhe in mm), Typ: NUMBER
#SDK (tägliche Sonnenscheindauer in Stunden h), Typ: NUMBER
#TMK (Tagesmittel der Lufttemperatur in 2m in °C), Typ: NUMBER

#alter versuch
#pd.merge(dftotal, df_wetter[[" RSK", " SDK", " TMK", " STATIONS_ID", " MESS_DATUM"]], left_on=["year", "month", "day"], right_on=["year", "month", "day"], how="left")

In [52]:
df_alles.head()

,segment_id,date_local,uptime,ped_lft,ped_rgt,ped_total,bike_lft,bike_rgt,bike_total,car_lft,...,car_speed60,car_speed70,day,month,year,RSK,SHK_TAG,TMK,STATIONS_ID,MESS_DATUM
0,9000003310,2022-03-18 07:00:00,0.752500,3,1,4,19,15,33,73,...,0.00,0.00,18,3,2022,0.0,-999,8.6,433,2022-03-18
1,9000003310,2022-03-18 08:00:00,0.797222,6,3,9,25,18,43,99,...,0.00,0.65,18,3,2022,0.0,-999,8.6,433,2022-03-18
2,9000003310,2022-03-18 09:00:00,0.795833,0,1,1,23,13,35,83,...,0.74,0.00,18,3,2022,0.0,-999,8.6,433,2022-03-18
3,9000003310,2022-03-18 10:00:00,0.805556,1,4,5,15,14,29,81,...,0.00,0.00,18,3,2022,0.0,-999,8.6,433,2022-03-18
4,9000003310,2022-03-18 11:00:00,0.596667,3,0,3,30,18,49,77,...,0.00,0.00,18,3,2022,0.0,-999,8.6,433,2022-03-18

In [53]:
#Lineare Regression:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

In [54]:
df_alles["stuendchen"]= df_alles["date_local"].dt.hour

In [55]:
# Features (X) und Ziel-Variable (y) definieren
X = df_alles[["RSK", "SHK_TAG", "TMK", "stuendchen"]]  # Wetterdaten als Features
y = df_alles["ped_total"]  # Fußgängerinnen als Ziel-Variable

In [56]:
df_alles.isna().sum()

segment_id        0
date_local        0
uptime            0
ped_lft           0
ped_rgt           0
ped_total         0
bike_lft          0
bike_rgt          0
bike_total        0
car_lft           0
car_rgt           0
car_total         0
heavy_lft         0
heavy_rgt         0
heavy_total       0
v85            2498
car_speed0        0
car_speed10       0
car_speed20       0
car_speed30       0
car_speed40       0
car_speed50       0
car_speed60       0
car_speed70       0
day               0
month             0
year              0
RSK               0
SHK_TAG           0
TMK               0
STATIONS_ID       0
MESS_DATUM        0
stuendchen        0
dtype: int64

In [57]:
# Train/Test Split (80% Training, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [58]:
# Daten normalisieren mit StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [59]:
# Lineares Regressionsmodell trainieren
model_linreg1 = LinearRegression()
model_linreg1.fit(X_train_scaled, y_train)

LinearRegression()

In [61]:
# Koeffizienten anzeigen / Gewichtungen
print("Modell-Koeffizienten:")
for feature, coef in zip(["RSK", "SHK_TAG", "TMK", "stuendchen"], model_linreg1.coef_):
    print(f"{feature:10s}: {coef:10.4f}")
print(f"Intercept: {model_linreg1.intercept_:10.4f}")

MODELL-KOEFFIZIENTEN
RSK       :    -1.2084
SHK_TAG   :     3.0866
TMK       :    -2.7231
stuendchen:     3.2208
Intercept:    18.9963

In [62]:
#wenn die Stunden steigen steigen auch die Anzahl der Fu´ganegerinnen
#Wenn viele Sonnenstunden gibt, dann stiegt die Anzahl der Fußgängerinnen
#Wenn die Niederschlagsmenge steigt, dann sinkt die Anzahl der Fußgängerinnen
#Intercept = Achsenabschnitt

In [63]:
# Vorhersagen machen
y_pred_train = model_linreg1.predict(X_train_scaled)
y_pred_test = model_linreg1.predict(X_test_scaled)

array([22.22646686, 13.90517543, 22.98557884, ..., 18.56883569,
       22.02156077, 12.05799919], shape=(10749,))

In [66]:
# Modell evaluieren
train_mae = mean_absolute_error(y_train, y_pred_train)
train_rmse = np.sqrt(mean_squared_error(y_train, y_pred_train))
train_r2 = r2_score(y_train, y_pred_train)

test_mae = mean_absolute_error(y_test, y_pred_test)
test_rmse = np.sqrt(mean_squared_error(y_test, y_pred_test))
test_r2 = r2_score(y_test, y_pred_test)


print("Model Evaluation")

print(f"{'Metrik':<15} {'Training':<15} {'Test':<15}")
print("-"*60)
print(f"{'MAE':<15} {train_mae:<15.2f} {test_mae:<15.2f}")
print(f"{'RMSE':<15} {train_rmse:<15.2f} {test_rmse:<15.2f}")
print(f"{'R²':<15} {train_r2:<15.4f} {test_r2:<15.4f}")

MODELL-EVALUATION
Metrik          Training        Test
------------------------------------------------------------
MAE             20.81           20.96
RMSE            37.09           41.30
R²              0.0209          0.0155

In [ ]:
#TODO: Random Forest Model fitten und gucken ob besser als lineare Regression ist(kann vlt auch missing values besser handhaben)
#können einfach left join machen statt inner join, dann hab ich n.a Werte und die sind kein problem für Random forest.

In [67]:
 #TODo: Lineare Regressionsmodell oghne pandemiezeitpunkt